### ISSUE TITLE
"torch._C._cuda_getDevice()" fails in Python3 but succeeds in Python2

### ISSUE THREAD

**Issue by aurotripathy** [ROCmSoftwarePlatform/pytorch#343]
**Python3**
```
root@0e76836e0bcf:/data/pytorch/examples/rl_a3c_pytorch# python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_getDevice()
THCudaCheck FAIL file=/pytorch/torch/csrc/cuda/Module.cpp line=53 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/torch/csrc/cuda/Module.cpp:53
>>> quit()

```

**Python2**

```
root@0e76836e0bcf:/data/pytorch/examples/rl_a3c_pytorch# python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_getDevice()
0L
>>> quit()
```

Python3 was built as follows:

First installed the following:

```
apt-get install python3-dev
apt-get install -y python3-pip
alias python=python3
```
then built with no changes

`.jenkins/pytorch/build.sh
`

**Comment by iotamudelta** [comment]
We do not currently support py3 but are working on that.

I do not recommend the approach you are taking. We will, in line with upstream, publish a correctly setup py3 docker image.

**Comment by aurotripathy** [comment]
Thanks @iotamudelta 

Is there a recommended (stop-gap) approach to building py3 support?

**Comment by Burstaholic** [comment]
The way I did it was modifying the critical line from the build script and running it directly:
`MAX_JOBS=4 USE_ROCM=1 USE_LMDB=1 USE_OPENCV=1 python3 setup.py install --user`

This will compile and install PyTorch if you've already 'hip-ified' the source. If not, `python tools/amd_build/build_amd.py` first (since it's in-place text replacement I think python version doesn't matter for that part).

Note for iotamudelta, this isn't related to my other issue, as I went through the PyTorch tutorial in a separate docker using Python 2 to keep it cleanly separated. This is just how I got ESRGAN to work, since it's written in Python 3.

**Comment by aurotripathy** [comment]
@Burstaholic,  thank you for the tips. Where I'm blocked with Python 3 is below:
```
>>> import torch
>>> torch._C._cuda_getDevice()
```
I'll be grateful is you could test the above in your environment.

**Comment by Burstaholic** [comment]
```
root@7e62640119e9:/# python3
Python 3.5.2 (default, Nov 12 2018, 13:43:14) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch._C._cuda_getDevice()
0
```

**Comment by aurotripathy** [comment]
Beautiful, hoping to get there with your steps.

**Comment by aurotripathy** [comment]
Closing this as ` rocm/pytorch:rocm2.2_ubuntu16.04_py3.6_pytorch` is now available. (#373)
Be sure to invoke with `python3.6 `if you use the container.
